# Generated by Django 4.0.4 on 2022-05-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0002_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
